#!/usr/bin/env bash

# Print the header

# Get version number
MB_VER=$(cat ../etc/version)

# Source the config file
source ../etc/config

echo ""
echo "#"
echo "##"
echo "### miner-boot ${MB_VER}"
echo "##"
echo "#"
echo ""
